# Generated by Django 5.1.6 on 2025-02-17 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del autor', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Breve biografía del autor')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la etiqueta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fintech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del artículo de fintech', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido detallado del artículo de fintech')),
                ('fecha_publicacion', models.DateField(blank=True, help_text='Fecha de publicación', null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.autor')),
                ('categorias', models.ManyToManyField(blank=True, to='blog.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='blog.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del artículo de inclusión financiera', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido detallado del artículo de inclusión financiera')),
                ('fecha_publicacion', models.DateField(blank=True, help_text='Fecha de publicación', null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.autor')),
                ('categorias', models.ManyToManyField(blank=True, to='blog.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='blog.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Sostenibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del artículo de sostenibilidad', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido detallado del artículo de sostenibilidad')),
                ('fecha_publicacion', models.DateField(blank=True, help_text='Fecha de publicación', null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.autor')),
                ('categorias', models.ManyToManyField(blank=True, to='blog.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='blog.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Texto del comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del comentario')),
                ('autor', models.ForeignKey(help_text='Usuario autor del comentario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sostenibilidad', models.ForeignKey(blank=True, help_text='Artículo de Sostenibilidad al que pertenece este comentario', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.sostenibilidad')),
            ],
        ),
    ]
